version: '3.4'

services:
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: 'untis_frontend'
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - untis_main

  cdn:
    image: nginx
    container_name: 'untis_cdn'
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - untis_main

networks:
  untis_main:
    driver: bridge